apiVersion: v1
kind: Service
metadata:
  name: fusion-content
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fusion-content.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  selector:
    app: fusion-content-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
