apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fusion-content.serverSAName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fusion-content.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
